name: Infra PR

on:
  pull_request:

permissions: {}

concurrency:
  group: infra-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    # no forks allowed
    if: (!github.event.pull_request.head.repo.fork)
    uses: ./.github/workflows/.infra-lint.yml

  plan:
    permissions:
      id-token: write # required for requesting the OIDC JWT
      contents: read # required for actions/checkout
    needs: [lint]
    if: (!github.event.pull_request.head.repo.fork)
    uses: ./.github/workflows/.infra.yml
    with:
      environment_name: test
      command: apply # apply for the time being when it is being proved out.
    secrets: inherit
